
---
#
# Shipping Microservice Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-host
  labels:
    app: sales-api
    tier: backend
spec:
  selector:
    matchLabels:
      app: shipping-host
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: shipping-host
        tier: backend
    spec:
      containers:
      - name: shipping-host
        image: $$REGISTRY_SERVERshipping-host:$$IMAGE_VERSION
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "$$ENVIRONMENT_NAME"
        - name: ASPNETCORE_ORCHESTRATOR
          value: "k8s"